// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqt704HlS5AXHeJqjvQ4-l-ltFi2EOucs',
    appId: '1:578925719705:web:47a85c4d38d25cc3720808',
    messagingSenderId: '578925719705',
    projectId: 'growiq-83513',
    authDomain: 'growiq-83513.firebaseapp.com',
    storageBucket: 'growiq-83513.firebasestorage.app',
    measurementId: 'G-YSFTET677L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBHDPBKddz02bJ0yojzJ722bXOmoFFZQ',
    appId: '1:578925719705:android:7d959815a658ba82720808',
    messagingSenderId: '578925719705',
    projectId: 'growiq-83513',
    storageBucket: 'growiq-83513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0uVjWavSMB8Z18RQRKyVb5Bc807DaIi8',
    appId: '1:578925719705:ios:4a24faf4763d6519720808',
    messagingSenderId: '578925719705',
    projectId: 'growiq-83513',
    storageBucket: 'growiq-83513.firebasestorage.app',
    iosBundleId: 'com.example.growiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0uVjWavSMB8Z18RQRKyVb5Bc807DaIi8',
    appId: '1:578925719705:ios:4a24faf4763d6519720808',
    messagingSenderId: '578925719705',
    projectId: 'growiq-83513',
    storageBucket: 'growiq-83513.firebasestorage.app',
    iosBundleId: 'com.example.growiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqt704HlS5AXHeJqjvQ4-l-ltFi2EOucs',
    appId: '1:578925719705:web:5203ebe9cf594b87720808',
    messagingSenderId: '578925719705',
    projectId: 'growiq-83513',
    authDomain: 'growiq-83513.firebaseapp.com',
    storageBucket: 'growiq-83513.firebasestorage.app',
    measurementId: 'G-SMN380HKS5',
  );
}
